/*
 * File: app/store/CommentStore.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.store.CommentStore', {
    extend: 'Ext.data.Store',

    requires: [
        'GURUAdmin.model.CommentModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 30,
            storeId: 'CommentStore',
            model: 'GURUAdmin.model.CommentModel',
            proxy: {
                type: 'ajax',
                url: '../api/comment/adminList',
                reader: {
                    type: 'json',
                    rootProperty: 'result',
                    totalProperty: 'totalCount'
                }
            }
        }, cfg)]);
    },

    clearExtraParams: function() {
        this.on('beforeload', function(store, options) {
            var queryParams = {
                "nick": null,
                "content":  null,
                "toDate": null,
                "fromDate": null
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
    }

});