/*
 * File: app/store/PostTypeStore.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.store.PostTypeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'PostTypeStore',
            data: [
                {
                    typeId: 0,
                    typeName: '短文'
                },
                {
                    typeId: 1,
                    typeName: '长文'
                },
                {
                    typeId: 2,
                    typeName: 'pdf文档'
                },
                {
                    typeId: -1,
                    typeName: '全部'
                }
            ],
            fields: [
                {
                    type: 'int',
                    name: 'typeId'
                },
                {
                    type: 'string',
                    name: 'typeName'
                }
            ]
        }, cfg)]);
    }
});