/*
 * File: app/view/ArticleEditWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.ArticleEditWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ArticleEditWindow',

    requires: [
        'GURUAdmin.view.ArticleEditWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.File',
        'Ext.Img',
        'Ext.button.Button',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'articleeditwindow'
    },
    height: 635,
    itemId: 'ArticleEditWindow',
    minWidth: 500,
    resizable: 'true;',
    bodyStyle: 'overflow-x:hidden;overflow-y:auto;',
    title: '文章编辑窗口',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 600,
            itemId: 'articleEditWinForm',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    id: 'articleWinId',
                    itemId: 'articleWinId',
                    width: 573,
                    fieldLabel: '文章Id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'articleWinClolumn',
                    itemId: 'articleWinClolumn',
                    width: 573,
                    fieldLabel: '栏目'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'articleWinTitle',
                    itemId: 'articleWinTitle',
                    width: 573,
                    fieldLabel: '标题'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    id: 'articleWinSummary',
                    itemId: 'articleWinSummary',
                    width: 573,
                    fieldLabel: '摘要'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'articleWinAuthor',
                    itemId: 'articleWinAuthor',
                    width: 573,
                    fieldLabel: '作者'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'articleWinShowFlag',
                    itemId: 'articleWinShowFlag',
                    width: 573,
                    fieldLabel: '标记位'
                },
                {
                    xtype: 'radiogroup',
                    id: 'display',
                    itemId: 'display',
                    width: 537,
                    fieldLabel: '显示',
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'display',
                            boxLabel: '不显示',
                            inputValue: 'n'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'display',
                            boxLabel: '显示',
                            inputValue: 'y'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    height: 244,
                    itemId: 'picUploadForm',
                    width: 537,
                    bodyPadding: '',
                    items: [
                        {
                            xtype: 'filefield',
                            anchor: '100%',
                            width: 517,
                            fieldLabel: '文章图片',
                            name: 'file',
                            buttonText: '选择图片'
                        },
                        {
                            xtype: 'form',
                            height: 211,
                            layout: 'column',
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 200,
                                    itemId: 'uploadImage',
                                    width: 420
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'picUploadBt',
                                    margin: 20,
                                    text: '上传'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'imageUrl',
                    itemId: 'imageUrl',
                    fieldLabel: '图片地址'
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    id: 'aticleWinDate',
                    itemId: 'aticleWinDate',
                    width: 573,
                    fieldLabel: '成为文章日期'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            height: '',
                            itemId: 'articleEditWinSubmitBt',
                            style: 'background:#22aee6;border:none;',
                            text: '提交'
                        }
                    ]
                }
            ]
        }
    ]

});