/*
 * File: app/view/ColumnAddWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.ColumnAddWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ColumnAddWindow',

    requires: [
        'GURUAdmin.view.ColumnAddWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'columnaddwindow'
    },
    height: 263,
    itemId: 'ColumnAddWindow',
    width: 389,
    title: '栏目新增窗口',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 202,
            itemId: 'columnAddForm',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'columnAddCode',
                    fieldLabel: '栏目编号',
                    name: 'code'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'columnAddName',
                    fieldLabel: '栏目名称',
                    name: 'name'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'columnAddSequence',
                    fieldLabel: '显示顺序',
                    name: 'sequence'
                },
                {
                    xtype: 'radiogroup',
                    id: 'columnAddWinStatus',
                    fieldLabel: '状态',
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'columnAddWinStatus',
                            boxLabel: '不显示',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'columnAddWinStatus',
                            boxLabel: '显示',
                            inputValue: '1'
                        }
                    ]
                },
                {
                    xtype: 'radiogroup',
                    id: 'columnAddWinType',
                    fieldLabel: '类型',
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'columnAddWinType',
                            boxLabel: '普通类型',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'columnAddWinType',
                            boxLabel: '媒体类型',
                            inputValue: '1'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 34,
                    itemId: 'columnAddWinTobar',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        align: 'stretchmax',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            frame: false,
                            height: 25,
                            itemId: 'columnAddSubmit',
                            style: 'background:#22aee6;border:none;',
                            text: '提交'
                        }
                    ]
                }
            ]
        }
    ]

});