/*
 * File: app/view/ColumnEditWindows.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.ColumnEditWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.ColumnEditWindows',

    requires: [
        'GURUAdmin.view.ColumnEditWindowsViewModel'
    ],

    viewModel: {
        type: 'columneditwindows'
    },
    height: 250,
    itemId: 'ColumnEditWindows',
    width: 400,
    title: '栏目编辑窗口'

});