/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LoginWindow',

    requires: [
        'GURUAdmin.view.LoginWindowViewModel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'loginwindow'
    },
    autoShow: true,
    height: 150,
    itemId: 'LoginWindow',
    width: 300,
    layout: 'form',
    title: '登陆',

    items: [
        {
            xtype: 'textfield',
            itemId: 'userName',
            fieldLabel: '用户名',
            value: 'admin'
        },
        {
            xtype: 'textfield',
            itemId: 'password',
            fieldLabel: '密码',
            inputType: 'password'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            border: '',
            frame: false,
            height: 57,
            ui: 'footer',
            width: 398,
            layout: {
                type: 'hbox',
                defaultMargins: {
                    top: 0,
                    right: 0,
                    bottom: 0,
                    left: 100
                }
            },
            items: [
                {
                    xtype: 'button',
                    height: 39,
                    itemId: 'loginButton',
                    style: 'margin-left:200px;',
                    width: 82,
                    text: '登陆'
                }
            ]
        }
    ]

});