/*
 * File: app/view/PostsDetailsWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.PostsDetailsWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.postsdetailswindow',

    requires: [
        'GURUAdmin.view.PostsDetailsWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'postsdetailswindow'
    },
    autoScroll: true,
    height: 630,
    hidden: false,
    itemId: 'PostsDetailsWindow',
    width: 860,
    layout: 'form',
    bodyStyle: 'overflow-x:hidden;overflow-y:auto;',
    collapsible: true,
    title: '帖子信息管理',
    modal: true,
    plain: true,

    items: [
        {
            xtype: 'form',
            height: 658,
            id: 'PostsWinForm',
            itemId: 'PostsWinForm',
            width: 822,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    hidden: true,
                    id: 'postId',
                    fieldLabel: '帖子id'
                },
                {
                    xtype: 'textfield',
                    id: 'postTitle',
                    width: 703,
                    fieldLabel: '标题'
                },
                {
                    xtype: 'textfield',
                    id: 'postUserName',
                    fieldLabel: '发帖人',
                    editable: false
                },
                {
                    xtype: 'datefield',
                    id: 'createDate',
                    fieldLabel: '发帖日期',
                    readOnly: false,
                    editable: false
                },
                {
                    xtype: 'timefield',
                    itemId: 'createTime',
                    fieldLabel: '发帖时间',
                    format: 'H:i s',
                    increment: 10
                },
                {
                    xtype: 'radiogroup',
                    id: 'postType',
                    width: '100%',
                    fieldLabel: '帖子类型',
                    columns: 3,
                    items: [
                        {
                            xtype: 'radiofield',
                            width: 100,
                            name: 'postType',
                            boxLabel: '短文',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            width: 100,
                            name: 'postType',
                            boxLabel: '长文',
                            inputValue: '1'
                        },
                        {
                            xtype: 'radiofield',
                            width: 100,
                            name: 'postType',
                            boxLabel: '研报',
                            inputValue: '2'
                        }
                    ]
                },
                {
                    xtype: 'radiogroup',
                    id: 'postStatus',
                    width: '100%',
                    fieldLabel: '帖子状态',
                    columns: 2,
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'postStatus',
                            boxLabel: '已删除',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'postStatus',
                            boxLabel: '正常',
                            inputValue: '1'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 435,
                    width: '100%',
                    fieldLabel: '内容',
                    items: [
                        {
                            xtype: 'htmleditor',
                            height: 454,
                            id: 'content',
                            width: '100%'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            itemId: 'postCommentWinGrid',
            width: '97%',
            rowLines: false,
            store: 'CommentStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: '18%',
                    dataIndex: 'nickname',
                    text: '评论人'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                        if(value!=null && value != ''){
                            return	 Ext.util.Format.date(new Date(value), "Y-m-d");
                        }
                    },
                    dataIndex: 'createDate',
                    text: '评论时间'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'content',
                    text: '评论内容'
                }
            ],
            dockedItems: [
                {
                    xtype: 'label',
                    dock: 'top',
                    style: 'font-size:12px;background:#f7f6f4;padding:5px 10px;',
                    width: 100,
                    text: '帖子评论'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    height: 24,
                    itemId: 'updatePost',
                    style: 'background:#22aee6;border:none;',
                    text: '保存更新'
                }
            ]
        }
    ]

});