/*
 * File: app/view/StockSelectWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.StockSelectWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.StockSelectWindow',

    requires: [
        'GURUAdmin.view.StockSelectWindowViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'stockselectwindow'
    },
    height: 610,
    id: 'StockSelectWindow',
    itemId: 'StockSelectWindow',
    width: 400,
    title: '股票选择',
    modal: true,

    items: [
        {
            xtype: 'gridpanel',
            itemId: 'StockSelectGrid',
            forceFit: true,
            store: 'StockSelectStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'stockName',
                    text: '股票名字'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'stockCode',
                    text: '股票代码'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'type',
                    text: '股票类型'
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    itemId: 'stockSelectConfirmBt',
                    text: '确定'
                },
                {
                    xtype: 'button',
                    itemId: 'stockSelectCancelBt',
                    text: '取消'
                }
            ]
        }
    ]

});