/*
 * File: app/view/UserDetailsWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.view.UserDetailsWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.UserDetailsWindow',

    requires: [
        'GURUAdmin.view.UserDetailsWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'userdetailswindow'
    },
    autoShow: true,
    height: 620,
    itemId: 'UserDetailsWindow',
    minHeight: 600,
    resizable: 'true;',
    weight: 15,
    width: 595,
    layout: 'column',
    bodyStyle: 'overflow-x:hidden;overflow-y:auto;',
    title: '用户信息查看',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 500,
            itemId: 'UserWinForm',
            minHeight: 300,
            resizable: true,
            width: 414,
            bodyPadding: '10px;',
            header: false,
            title: 'My Form',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'userName',
                    margin: '15 5 5 5;',
                    fieldLabel: '用户名',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    id: 'userId',
                    margin: '5 5;',
                    width: 150,
                    fieldLabel: '用户id',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    id: 'nick',
                    margin: '5 5;',
                    width: 150,
                    fieldLabel: '昵称',
                    labelWidth: 60
                },
                {
                    xtype: 'radiogroup',
                    height: 28,
                    id: 'sex',
                    margin: '5 5;',
                    width: 378,
                    fieldLabel: '性别',
                    columns: 2,
                    items: [
                        {
                            xtype: 'radiofield',
                            width: 70,
                            name: 'sex',
                            boxLabel: '男',
                            inputValue: 'M'
                        },
                        {
                            xtype: 'radiofield',
                            width: 70,
                            name: 'sex',
                            boxLabel: '女',
                            inputValue: 'F'
                        }
                    ]
                },
                {
                    xtype: 'radiogroup',
                    height: 39,
                    id: 'status',
                    margin: '5 5;',
                    fieldLabel: '用户状态',
                    items: [
                        {
                            xtype: 'radiofield',
                            width: 70,
                            name: 'status',
                            boxLabel: '未激活',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            width: 70,
                            name: 'status',
                            boxLabel: '已激活',
                            inputValue: '1'
                        },
                        {
                            xtype: 'radiofield',
                            width: 70,
                            name: 'status',
                            boxLabel: '已关闭',
                            inputValue: '2'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    height: 25,
                    id: 'phone',
                    margin: '5 5;',
                    fieldLabel: '手机号码',
                    labelWidth: 60,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    height: 25,
                    id: 'email',
                    margin: '5 5;',
                    fieldLabel: '电子邮箱',
                    labelWidth: 60,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    height: 25,
                    id: 'regIp',
                    margin: '5 5;',
                    fieldLabel: '注册ip',
                    labelWidth: 60,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    height: 25,
                    id: 'regFrom',
                    margin: '5 5;',
                    fieldLabel: '注册来源',
                    labelWidth: 60,
                    editable: false
                },
                {
                    xtype: 'datefield',
                    height: 25,
                    id: 'birth',
                    margin: '5 5;',
                    fieldLabel: '出生日期',
                    labelWidth: 60
                },
                {
                    xtype: 'fieldcontainer',
                    height: 18,
                    id: 'location',
                    margin: '5 5;',
                    width: '100%',
                    layout: 'table',
                    items: [
                        {
                            xtype: 'combobox',
                            height: 25,
                            id: 'country',
                            itemId: 'country',
                            width: 138,
                            fieldLabel: '所在地',
                            labelWidth: 60,
                            displayField: 'name',
                            store: 'CountryStore',
                            valueField: 'code'
                        },
                        {
                            xtype: 'combobox',
                            height: 25,
                            id: 'state',
                            itemId: 'state',
                            width: 128,
                            fieldLabel: '省(州)',
                            labelWidth: 40,
                            readOnly: true,
                            editable: false,
                            displayField: 'name',
                            store: 'StateStore',
                            valueField: 'code'
                        },
                        {
                            xtype: 'combobox',
                            height: 25,
                            id: 'city',
                            itemId: 'city',
                            width: 118,
                            fieldLabel: '城市',
                            labelWidth: 30,
                            readOnly: true,
                            editable: false,
                            displayField: 'name',
                            store: 'CityStore',
                            valueField: 'code'
                        }
                    ]
                },
                {
                    xtype: 'textareafield',
                    height: 100,
                    id: 'userBrief',
                    margin: '10 5;',
                    fieldLabel: '用户简介',
                    labelWidth: 60
                }
            ]
        },
        {
            xtype: 'image',
            height: 100,
            id: 'avatar',
            itemId: 'avatar',
            margin: '5 20;',
            width: 120,
            alt: '用户头像',
            src: 'images/user.png'
        },
        {
            xtype: 'gridpanel',
            itemId: 'UProfessionWinGrid',
            width: 590,
            bodyPadding: '10px;',
            store: 'UProfessionStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: '60%',
                    dataIndex: 'professions',
                    text: '行业'
                },
                {
                    xtype: 'gridcolumn',
                    width: '35%',
                    dataIndex: 'time',
                    text: '年长'
                }
            ],
            viewConfig: {
                itemId: 'UProfessionWinGridView'
            },
            dockedItems: [
                {
                    xtype: 'label',
                    dock: 'top',
                    height: 23,
                    style: 'font-size:12px;background:#f7f6f4;padding:5px 10px;',
                    width: 100,
                    text: '行业经验'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            height: 34,
            ui: 'footer',
            width: 560,
            layout: {
                type: 'hbox',
                align: 'stretchmax',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    frame: false,
                    height: 25,
                    itemId: 'UpdateUser',
                    margin: '0 235;',
                    style: 'background:#22aee6;border:none;',
                    text: '保存更新'
                }
            ]
        }
    ]

});