/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PagerDemo.view.MyContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.mycontainer',

    requires: [
        'PagerDemo.view.MyContainerViewModel',
        'Ext.grid.Panel',
        'Ext.grid.filters.Filters',
        'Ext.grid.filters.filter.String',
        'Ext.grid.column.Number',
        'Ext.grid.filters.filter.Number',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'mycontainer'
    },
    height: 380,
    width: 560,
    layout: 'fit',

    items: [
        {
            xtype: 'gridpanel',
            title: 'My Grid Panel',
            store: 'UserStore',
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'mail',
                    text: 'Mail',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'age',
                    text: 'Age',
                    filter: {
                        type: 'number'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'UserStore'
                }
            ]
        }
    ]

});