/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'UserModel',
        'InvitionCodeModel',
        'ColumnModel',
        'PostsModel',
        'InvitationCodeUserDetailModel',
        'MediaArticleModel',
        'RelationStockModel',
        'PostStockRelationModel',
        'StockSelectModel',
        'BizLogModel',
        'BizLogTypeModel'
    ],
    stores: [
        'GMenuStore',
        'UserStore',
        'InvitionCodeStore',
        'CountryStore',
        'CityStore',
        'StateStore',
        'UProfessionStore',
        'PostsStore',
        'ArticleStore',
        'CommentStore',
        'PostTypeStore',
        'PostStatusStore',
        'HeatViewStore',
        'HeatviewTypeStore',
        'InvitationCodeUserDetailStore',
        'MediaArticleStore',
        'UserTypeStore',
        'RelationStockStore',
        'PostStockRelationStore',
        'StockSelectStore',
        'ColumnStore',
        'BizLogStore',
        'BizLogTypeStore'
    ],
    views: [
        'MainViewport',
        'UserDetailsWindow',
        'ColumnAddWindow',
        'ColumnEditWindow',
        'ArticleDetailWindow',
        'PostsDetailsWindow',
        'CommentDetailsWindow',
        'AddHeatViewWindow',
        'EditHeatViewWindow',
        'PushWindow',
        'StockSelectWindow',
        'LoginWindow'
    ],
    controllers: [
        'LoginController',
        'MainViewController',
        'UserController',
        'InvitationCodeController',
        'ColumnController',
        'ArticleController',
        'PostsController',
        'CommentsController',
        'HeatViewController',
        'ConfigController',
        'Ga100Controller',
        'MediaArticleController',
        'RelationStockController',
        'PostStockRelationController',
        'StockSelectController',
        'BizLogController'
    ],
    name: 'GURUAdmin',

    /* EXT应用加载 */
    launch: function() {

        var me = this;
        Ext.Ajax.request({
            url:"../api/admin/isLogin",
            success:function(response){
                var resp = Ext.util.JSON.decode(response.responseText);
                if(resp.result == true){
                    var app = GURUAdmin.getApplication();
                    me.loadData();

                    var username = resp.message;
                    var mainView = Ext.create('GURUAdmin.view.MainViewport');

                    var currentUserItem = mainView.getComponent("HeaderPanel").getComponent("headerToolBar").getComponent("currentUser");
                    currentUserItem.setText(username);

                }else{
                    Ext.create('GURUAdmin.view.LoginWindow', {renderTo: Ext.getBody()});
                }
            }
        });
    },

    /* 登陆之后所要加载的数据 //TOFIX 代码冗余，和loginController的loadData相同 */
    loadData: function() {




        //menu
        Ext.Ajax.request({
            url : "../api/menu/getMenuTree",
            method : 'POST',
            success : function(resp) {
                var obj = Ext.util.JSON.decode(resp.responseText);
                var menuStore = Ext.data.StoreManager.lookup("GMenuStore");
                var root = menuStore.getRoot();
                root.removeAll();
                root.appendChild(obj.result);
            }
        });

        var postStore = Ext.data.StoreManager.lookup("PostsStore");
        postStore.load({
            params : {
                "start" : 0,
                "limit" : postStore.pageSize
            },

            callback : function(records, operation, success) {
                if (!success) {
                    Ext.MessageBox.alert('Error', "数据获取失败", null, null);
                }
            }
        });



    }

});
