/*
 * File: app/model/ColumnModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.model.ColumnModel', {
    extend: 'Ext.data.Model',
    alias: 'model.ColumnModel',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'columnCode'
        },
        {
            name: 'columnName'
        },
        {
            name: 'sequence'
        },
        {
            name: 'status'
        },
        {
            name: 'type'
        }
    ]
});