/*
 * File: app/model/UserModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.model.UserModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'userId'
        },
        {
            name: 'userName'
        },
        {
            name: 'email'
        },
        {
            name: 'phone'
        },
        {
            name: 'userBrief'
        },
        {
            name: 'regIp'
        },
        {
            name: 'regFrom'
        },
        {
            name: 'sex'
        },
        {
            name: 'birth'
        },
        {
            name: 'country'
        },
        {
            name: 'city'
        },
        {
            name: 'nick'
        },
        {
            name: 'state'
        },
        {
            name: 'avatar'
        },
        {
            name: 'roleId'
        },
        {
            name: 'userType'
        }
    ]
});