'use strict';
GLHApp.config(['$routeProvider', '$locationProvider', function ($routeProvider, $locationProvider) {
    $routeProvider.when('/', {
        templateUrl: 'views/homeBeta.html'
    }).when('/register', {
        templateUrl: 'views/userRegister.html'
    }).when('/userHome', {
        templateUrl: 'views/userHome.html'
    }).when('/userContent', {
        templateUrl: 'views/userContent.html'
    }).when('/userMessage', {
        templateUrl: 'views/userMessage.html'
    }).when('/commentMe', {
        templateUrl: 'views/userCommentMe.html'
    }).when('/referMe', {
        templateUrl: 'views/userReferMe.html'
    }).when('/userFavorite', {
        templateUrl: 'views/userFavorite.html'
    }).when('/userAttention', {
        templateUrl: 'views/userAttention.html'
    }).when('/userFans', {
        templateUrl: 'views/userFans.html'
    }).when('/userUpdate/:type/:userId', {
    	templateUrl: 'views/updateUserInfo.html'
    }).when('/userInfo/:userId', {
        templateUrl: 'views/userInfo.html'
    }).when('/updatePwd', {
        templateUrl: 'views/updatePwd.html'
    }).when('/updatePwdByEmail/:activeCode/:email', {
        templateUrl: 'views/updatePwdEmail.html'
    }).when('/topic/:topicCode', {
        templateUrl: 'views/topic.html'
    }).when('/articleDetail/:postId', {
        // 或者
        templateUrl: function(routeParams,path,search){
            return "p/"+routeParams.postId+".html?status=0"
        } 
    }).when('/activeEmail/:userId/:activeCode/:inviteCode', {
        templateUrl: 'views/activeEmail.html'
    }).when('/error', {
        templateUrl: 'views/error.html'
    }).when('/error/:errorType', {
        templateUrl: 'views/error.html'
    }).when('/error/:errorType/:code', {
        templateUrl: 'views/error.html'
    }).when('/search', { 
        templateUrl: 'views/searchPost.html'
    }).when('/searchStock', {
        templateUrl: 'views/searchStock.html'
    }).when('/searchUser', {
        templateUrl: 'views/searchUser.html'
    }).when('/searchMore', {
        templateUrl: 'views/searchMore.html'
    }).when('/search/:key', {
        templateUrl: 'views/searchPost.html'
    }).when('/searchStock/:key', {
        templateUrl: 'views/searchStock.html'
    }).when('/searchUser/:key', {
        templateUrl: 'views/searchUser.html'
    }).when('/searchMore/:key', {
        templateUrl: 'views/searchMore.html'
    }).when('/searchGicsII/:key', {
        templateUrl: 'views/searchGicsII.html'
    }).when('/searchGicsII', {
        templateUrl: 'views/searchGicsII.html'
    }).when('/searchGicsCompany/:key', {
        templateUrl: 'views/searchGicsCompany.html'
    }).when('/searchGicsCompany/:key', {
        templateUrl: 'views/searchGicsCompany.html'
    }).when('/success/:type', {
        templateUrl: 'views/success.html'
    }).when('/relief', {
        templateUrl: 'views/relief.html'
    }).when('/contactUs', {
        templateUrl: 'views/contactUs.html'
    }).when('/introduction', {
        templateUrl: 'views/introduction.html'
    }).when('/introduction/:type', {
        templateUrl: 'views/introduction.html'
    }).when('/stockDetail/:stockCode', {
        templateUrl: 'views/stockDetail.html'
    }).when('/f10', {
        templateUrl: 'views/f10charts.html'
    }).when('/glhExponent/:code', {
        templateUrl: 'views/glhExponent.html'
    }).when('/recommendedUsers', {
        templateUrl: 'views/secondEdition/recommendedUsers.html'
    }).when('/stockPage/:stockCode', {
        templateUrl: 'views/secondEdition/stockPage.html'
    }).otherwise({ redirectTo: '/' });
    //$locationProvider.html5Mode(true);
}]);