/*
 * File: app/controller/ConfigController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.controller.ConfigController', {
    extend: 'Ext.app.Controller',

    refs: {
        configFormPanel: '#ConfigFormPanel',
        setEssenceLimitBt: '#setEssenceLimitBt',
        setSensitiveWordBt: '#setSensitiveWordBt',
        setDomain: '#setDomain'
    },

    control: {
        "#setEssenceLimitBt": {
            click: 'onSetEssenceLimitBtClick'
        },
        "#setSensitiveWordBt": {
            click: 'onSetSensitiveWordBtClick'
        },
        "#setDomain": {
            click: 'onSetDomainClick'
        }
    },

    onSetEssenceLimitBtClick: function(button, e, eOpts) {
        var me = this;
        var value = me.getConfigFormPanel().getForm().findField("essenceLimit").value;
        me.setCfgProperty("ESSENCE_LIMIT",value,null);
    },

    onSetSensitiveWordBtClick: function(button, e, eOpts) {
        var me = this;
        var value = me.getConfigFormPanel().getForm().findField("sensitiveWord").value;
        me.setCfgProperty("SENSITIVE_WORD",value,null);
    },

    onSetDomainClick: function(button, e, eOpts) {
        var me = this;
        var value = me.getConfigFormPanel().getForm().findField("domain").value;
        me.setCfgProperty("DOMAIN",value,null);
    },

    setCfgProperty: function(key, value, desc) {
        var temp = {
            "key": key,
            "value":value,
            "desc":desc
        };
        Ext.Ajax.request({
            params: Ext.encode(temp),
            headers: {
                'Content-Type': 'application/json'
            },
            url: "../api/config/set",
            method: 'POST',
            success: function (resp) {
                var obj = Ext.util.JSON.decode(resp.responseText);
                Ext.MessageBox.alert('更新操作', obj.message);
            }
        });//
    }

});
