/*
 * File: app/controller/InvitationCodeController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.controller.InvitationCodeController', {
    extend: 'Ext.app.Controller',

    models: [
        'InvitionCodeModel'
    ],
    stores: [
        'InvitionCodeStore'
    ],

    refs: {
        addInvitionCodBt: '#addInvitionCodBt',
        invitationUserListGrid: '#InvitationUserListGrid',
        invitationCodeQueryBt: '#invitationCodeQueryBt',
        invitationCodeQueryUsername: '#invitationCodeQueryUsername',
        invitationCodeQueryNick: '#invitationCodeQueryNick',
        invitationCodeUserDetailQeruyBt: '#invitationCodeUserDetailQeruyBt',
        invitationCodeDetailListQueryForm: '#invitationCodeDetailListQueryForm',
        invitationUserDetailGrid: '#InvitationUserDetailGrid',
        userInvitationDetailBt: '#userInvitationDetailBt',
        invitationCodeQueryPanel: '#invitationCodeQueryPanel'
    },

    control: {
        "#addInvitionCodBt": {
            click: 'onAddInvitionCodBtClick'
        },
        "#invitationCodeQueryBt": {
            click: 'onInvitationCodeQueryBtClick'
        },
        "#invitationCodeUserDetailQeruyBt": {
            click: 'onInvitationCodeUserDetailQeruyBtClick'
        },
        "#InvitationUserListGrid": {
            beforehide: 'onInvitationUserListGridBeforeHide'
        },
        "#InvitationUserDetailGrid": {
            hide: 'onInvitationUserDetailGridHide'
        }
    },

    /* 栏目列表界面新增按钮事件 */
    onAddInvitionCodBtClick: function(button, e, eOpts) {
        var selectionModel = this.getInvitationUserListGrid().getSelectionModel();
        var invitationStore = this.getInvitationUserListGrid().getStore();
        var record = selectionModel.getSelection();
        var inviterId = record[0].data.inviterId;
        var nick = record[0].data.nick;
        var addNum ;
        if (record === null || record === undefined || record.length === 0) {
            Ext.MessageBox.alert('未选中', "请选中一行");
        }else{
            //新建窗口并显示
            var _window = Ext.create('Ext.window.Window',{
                title: "登陆",
                renderTo: Ext.getBody(),
                frame: true,
                plain: true,
                resizable: false,
                buttonAlign: "right",
                closable: true,
                model:true,
                bodyStyle: "padding:4px",
                width: 310,
                height: 230,
                layout: "form",
                lableWidth: 45,
                defaults: {
                    xtype: "textfield",
                    width: 180
                },
                items: [{
                    fieldLabel: "用户名",
                    value: nick ,
                    id:"username",
                    readOnly: true,
                },
                        {
                            fieldLabel: "邀请码的添加个数",
                            id:"addNum"
                        }],
                buttons: [{
                    text: "确定",
                    handler:function(){
                        addNum = Ext.getCmp('addNum').value;
                        //发送Ajax请求添加邀请码
                        Ext.Ajax.request({
                            url: '../api/invitationCode/add?amount='+addNum+'&inviterId='+inviterId,
                            headers : {
                                'Content-Type' : 'application/json'
                            },
                            method : 'POST',
                            success: function(response){
                                invitationStore.reload();
                            }
                        });
                        _window.close();
                    }
                },
                          {
                              text: "取消",
                              handler: function() {
                                  _window.close();
                              }
                          }]
            }).show();
        }
    },

    /* 邀请码用户统计列表页面的查询按钮事件 */
    onInvitationCodeQueryBtClick: function(button, e, eOpts) {
        var invitationStore = this.getInvitationUserListGrid().getStore();
        var username = this.getInvitationCodeQueryUsername().getValue();
        var nick = this.getInvitationCodeQueryNick().getValue();
        invitationStore.on('beforeload', function(store, options) {
            var queryParams = {
                "username": username,
                "nick":  nick
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
        invitationStore.loadPage(1);
    },

    /* 邀请码用户详细信息的列表查询按钮事件 */
    onInvitationCodeUserDetailQeruyBtClick: function(button, e, eOpts) {
        var invitationUserDetailGrid = this.getInvitationUserDetailGrid();
        var invitationCodeDetailListQueryForm = this.getInvitationCodeDetailListQueryForm().getForm();
        var store = Ext.data.StoreManager.lookup("InvitationCodeUserDetailStore");
        store.on('beforeload', function(store, options) {
            var queryParams = {
                "inviterNick" : invitationCodeDetailListQueryForm.findField('inviterNick').getValue()
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
        store.loadPage(1);
    },

    /* 统计列表隐藏前触发的事件 */
    onInvitationUserListGridBeforeHide: function(component, eOpts) {
        var invitationCodeQueryPanel = this.getInvitationCodeQueryPanel();
        var store = this.getInvitationUserListGrid().getStore();
        store.clearExtraParams();
        invitationCodeQueryPanel.reset();
    },

    onInvitationUserDetailGridHide: function(component, eOpts) {
        var form = this.getInvitationCodeDetailListQueryForm();
        form.reset();
    }

});
