/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.controller.LoginController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.logincontroller',

    refs: {
        userName: '#userName',
        loginButton: '#loginButton',
        headerPanel: '#headerPanel',
        menuPanel: '#MenuPanel',
        gMainPanel: '#GMainPanel',
        loginWindow: '#LoginWindow',
        password: '#password'
    },

    control: {
        "#loginButton": {
            click: 'onLoginButtonClick'
        }
    },

    onLoginButtonClick: function(button, e, eOpts) {
        var me = this;
        this.loginVerify(me);//
    },

    /* 登陆验证 */
    loginVerify: function(me) {
        var userName = me.getUserName().value;
        var temp = {
            "userName":userName,
            "password" : me.getPassword().value
        };

        Ext.Ajax.request({
            params : Ext.encode(temp),
            url : "../api/admin/login",
            headers : {
                'Content-Type' : 'application/json'
            },
            method : 'POST',
            success : function(resp){
                var result = Ext.decode(resp.responseText);
                if(result.statusCode == 200){

                    me.loadData();
                    var mainView = Ext.create('GURUAdmin.view.MainViewport');
                    var currentUserItem = mainView.getComponent("HeaderPanel").getComponent("headerToolBar").getComponent("currentUser");
                    currentUserItem.setText(userName);
                    me.getLoginWindow().close();
                }else{
                    Ext.MessageBox.alert('Error', result.message);
                }
            }
        });
    },

    getMenuData: function(me) {

    },

    /* 加载用户列表以及菜单栏的数据 */
    loadData: function() {

        /*var userStore = Ext.data.StoreManager.lookup("UserStore");
        userStore.removeAll();
        userStore.load({
            params : {
                "start" : 0,
                "limit" : userStore.pageSize
            },

            callback : function(records, operation, success) {
                if (!success) {
                    Ext.MessageBox.alert('Error', "数据获取失败", null, null);
                }
            }
        });*/
        //menu
        Ext.Ajax.request({
            url : "../api/menu/getMenuTree",
            method : 'POST',
            success : function(resp) {
                var obj = Ext.util.JSON.decode(resp.responseText);
                var menuStore = Ext.data.StoreManager.lookup("GMenuStore");
                var root = menuStore.getRoot();
                root.removeAll();
                root.appendChild(obj.result);
            }
        });
        var postStore = Ext.data.StoreManager.lookup("PostsStore");
        //postStore.removeAll();
        postStore.load({
            params : {
                "start" : 0,
                "limit" : postStore.pageSize
            },

            callback : function(records, operation, success) {
                if (!success) {
                    Ext.MessageBox.alert('Error', "数据获取失败", null, null);
                }
            }
        });
        /*
        //commentsStore
        Ext.Ajax.request({
            url: "../api/comment/adminList",
            method: 'GET',
            success: function (resp) {
                var obj = Ext.util.JSON.decode(resp.responseText);
                var commentStore = Ext.data.StoreManager.lookup("CommentStore");
                commentStore.removeAll();
                commentStore.loadData(obj.result);
            }
        });
        */
    }

});
