/*
 * File: app/controller/MediaArticleController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.controller.MediaArticleController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.MediaArticleController',

    refs: {
        mArticleReflashBt: '#mArticleReflashBt',
        mArticleGirdShowBt: '#mArticleGirdShowBt',
        mediaArticleGridPanel: '#MediaArticleGridPanel',
        mArticleGridDeleteBt: '#mArticleGridDeleteBt',
        mArticleGridQueryBt: '#mArticleGridQueryBt',
        mArticelGridQueryForm: '#mArticelGridQueryForm',
        mArticleGridDetailBt: '#mArticleGridDetailBt',
        annNoticeRefreshBt: '#annNoticeRefreshBt',
        stockRefreshBt: '#stockRefreshBt'
    },

    control: {
        "#mArticleReflashBt": {
            click: 'onMArticleReflashBtClick'
        },
        "#mArticleGirdShowBt": {
            click: 'onMArticleGirdShowBtClick'
        },
        "#mArticleGridDeleteBt": {
            click: 'onMArticleGridDeleteBtClick'
        },
        "#mArticleGridQueryBt": {
            click: 'onMArticleGridQueryBtClick'
        },
        "#mArticleGridDetailBt": {
            click: 'onMArticleGridDetailBtClick'
        },
        "#annNoticeRefreshBt": {
            click: 'onAnnNoticeRefreshBtClick'
        },
        "#stockRefreshBt": {
            click: 'onStockRefreshBtClick'
        },
        "#MediaArticleGridPanel": {
            beforehide: 'onMediaArticleGridPanelBeforeHide'
        }
    },

    /* 公众号文章更新按钮事件 */
    onMArticleReflashBtClick: function(button, e, eOpts) {
        var me = this;
        Ext.Ajax.request({
            url: '../api/spider/media/article/refresh',
            headers : {
                'Content-Type' : 'application/json'
            },
            method : 'GET',
            success: function(response){
                var result=Ext.util.JSON.decode(response.responseText);
                if(result.statusCode==200){
                    Ext.Msg.alert('成功', result.message);
                    me.getMediaArticleGridPanel().getStore().reload();
                }else{
                    Ext.Msg.alert('失败', '更新失败,原因是:'+result.message);
                }
            }
        });
    },

    /* 公众号文章列表页面显示/不显示按钮事件 */
    onMArticleGirdShowBtClick: function(button, e, eOpts) {
        var me = this;
        var selectionModel = me.getMediaArticleGridPanel().getSelectionModel();
        var records = selectionModel.getSelection();
        if (records == null || records == undefined || records.length == 0) {
            Ext.MessageBox.alert('未选中', "请选中一行");
        } else {
            var ids = "";
            for (var i = 0; i < records.length; i++) {
                //ids.push(records[i].get('articleId'));
                ids = ids + records[i].get('articleId')+",";
            }
        }
        ids = ids.substring(0,ids.length-1);
        Ext.Ajax.request({
            url: '../api/spider/media/article/update/show?mArticleIds='+ids,
            headers : {
                'Content-Type' : 'application/json'
            },
            method : 'POST',
            params: ids,
            success: function(response){
                var result=Ext.util.JSON.decode(response.responseText);
                if(result.statusCode==200){
                    Ext.Msg.alert('修改成功', result.message);
                    me.getMediaArticleGridPanel().getStore().reload();
                }else{
                    Ext.Msg.alert('失败', '更新失败,原因是:'+result.message);
                }
            }
        });
    },

    /* 公众号文章列表删除按钮事件 */
    onMArticleGridDeleteBtClick: function(button, e, eOpts) {
        var me = this;
        var selectionModel = me.getMediaArticleGridPanel().getSelectionModel();
        var records = selectionModel.getSelection();
        if (records == null || records == undefined || records.length == 0) {
            Ext.MessageBox.alert('未选中', "请选中一行");
        } else {
            var ids = "";
            for (var i = 0; i < records.length; i++) {
                ids = ids + records[i].get('articleId')+",";
            }
        }
        ids = ids.substring(0,ids.length-1);
        Ext.Ajax.request({
            url: '../api/spider/media/article/delete/'+ids,
            headers : {
                'Content-Type' : 'application/json'
            },
            method : 'POST',
            success: function(response){
                var result=Ext.util.JSON.decode(response.responseText);
                if(result.statusCode==200){
                    Ext.Msg.alert('删除成功', result.message);
                    me.getMediaArticleGridPanel().getStore().reload();
                }else{
                    Ext.Msg.alert('失败', '删除失败,原因是:'+result.message);
                }
            }
        });
    },

    /* 媒体文章条件查询 */
    onMArticleGridQueryBtClick: function(button, e, eOpts) {
        var me = this;
        var store = me.getMediaArticleGridPanel().getStore();
        var formPanel = me.getMArticelGridQueryForm();
        var form = formPanel.getForm();

        store.on('beforeload', function(store, options) {
            var showFlagBoolean = form.findField("mArticleShowFlag").getValue();
            if(showFlagBoolean == false){
                showFlag = 0;
            }else{
                showFlag = 1;
            }

            var queryParams = {
                "mAticleTitle":form.findField("articleTitle").getValue(),
                "mediaName":form.findField("mediaName").getValue(),
                "showFlag":showFlag,
                "recordDate":form.findField("recordDate").getValue()
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
        store.loadPage(1);

    },

    /* 媒体文章列表查看详细事件 */
    onMArticleGridDetailBtClick: function(button, e, eOpts) {
        var mArticleListGrid = this.getMediaArticleGridPanel();
        var selectionModel = mArticleListGrid.getSelectionModel();
        var record = selectionModel.getSelection();
        if (record === null || record === undefined || record.length === 0) {
            Ext.MessageBox.alert('未选中', "请选中一行");
            return ;
        }
        window.open(record[0].data.articleUrl);
    },

    /* 股票公告刷新按钮事件 */
    onAnnNoticeRefreshBtClick: function(button, e, eOpts) {
        Ext.Ajax.request({
            url: '../api/spider/annNotice/refresh',
            headers : {
                'Content-Type' : 'application/json'
            },
            method : 'POST',
            success: function(response){
                var result=Ext.util.JSON.decode(response.responseText);
                if(result.statusCode==200){
                    Ext.Msg.alert('刷新成功', result.message);
                }else{
                    Ext.Msg.alert('失败', '刷新失败,原因是:'+result.message);
                }
            }
        });
    },

    /* 股票刷新按钮事件 */
    onStockRefreshBtClick: function(button, e, eOpts) {
        Ext.Ajax.request({
            url: '../api/spider/stock/refresh',
            headers : {
                'Content-Type' : 'application/json'
            },
            method : 'POST',
            success: function(response){
                var result=Ext.util.JSON.decode(response.responseText);
                if(result.statusCode==200){
                    Ext.Msg.alert('刷新成功', result.message);
                }else{
                    Ext.Msg.alert('失败', '刷新失败,原因是:'+result.message);
                }
            }
        });
    },

    onMediaArticleGridPanelBeforeHide: function(component, eOpts) {
        this.getMArticelGridQueryForm().reset();
    }

});
