/*
 * File: app/controller/PostStockRelationController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.controller.PostStockRelationController', {
    extend: 'Ext.app.Controller',

    refs: {
        postStockRelationFormPanel: '#PostStockRelationFormPanel',
        postStockRelationGrid: '#PostStockRelationGrid',
        postStockRelationQueryStockCodeQuery: '#postStockRelationQueryStockCodeQuery',
        stockSelectGrid: '#StockSelectGrid',
        postStockRelationGridAddBt: '#PostStockRelationGridAddBt'
    },

    control: {
        "#PostStockRelationQuertBt": {
            click: 'onPostStockRelationQuertBtClick'
        },
        "#postStockRelationQueryStockCodeQuery": {
            click: 'onPostStockRelationQueryStockCodeQueryClick'
        },
        "#PostStockRelationGridAddBt": {
            click: 'onPostStockRelationGridAddBtClick'
        },
        "#PostStockRelationGrid": {
            beforehide: 'onPostStockRelationGridBeforeHide'
        }
    },

    /* 帖子股票关联界面搜索帖子事件 */
    onPostStockRelationQuertBtClick: function(button, e, eOpts) {
        var postStockRelationStore = this.getPostStockRelationGrid().getStore();
        var form = this.getPostStockRelationFormPanel().getForm();
        postStockRelationStore.on('beforeload', function(store, options) {
            var queryParams = {
                key : form.findField('postStockRelationPostTitle').getValue()
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
        postStockRelationStore.loadPage(1);
    },

    /* 帖子股票关联界面搜索股票事件 */
    onPostStockRelationQueryStockCodeQueryClick: function(button, e, eOpts) {
        var win = Ext.getCmp("StockSelectWindow");
        if(win == null){
            win = Ext.create("GURUAdmin.view.StockSelectWindow");
        }

        var store = this.getStockSelectGrid().getStore();
        var form = this.getPostStockRelationFormPanel().getForm();
        store.on('beforeload', function(store, options) {
            var queryParams = {
                keyword: form.findField('postStockRelationStock').getValue(),
                count : 20
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
        store.loadPage(1);
        win.show();
    },

    /* 帖子股票关联界面"关联"按钮事件 */
    onPostStockRelationGridAddBtClick: function(button, e, eOpts) {
        var me=this;
        if(me.getStockSelectGrid()  == null || me.getStockSelectGrid() == undefined){
            Ext.MessageBox.alert('未选中股票', "请选中一行");
            return ;
        }
        var stockSelectionModel = me.getStockSelectGrid().getSelectionModel();
        var stockRecord = stockSelectionModel.getSelection();
        if (stockRecord === null || stockRecord === undefined || stockRecord.length === 0) {
            Ext.MessageBox.alert('未选中股票', "请选中一行");
            return ;
        }
        var stockData = stockRecord[0].data;
        var postSelectionModel = me.getPostStockRelationGrid().getSelectionModel();
        if (stockRecord === null || stockRecord === undefined || stockRecord.length === 0) {
            Ext.MessageBox.alert('未选中帖子', "请选中一行");
            return ;
        }
        var postRecords = postSelectionModel.getSelection();
        var postIdArray = new Array();
        for (var i = 0; i < postRecords.length; i++) {
            postIdArray[i]=postRecords[i].get('postId');
        }
        var params = {
            "stockCode":stockData.type+stockData.stockCode,
            "postIds":postIdArray
        };
        Ext.Ajax.request({
            url: '../api/post/stockRelation/add',
            headers: {
                'Content-Type': 'application/json'
            },
            method : 'POST',
            params: Ext.encode(params),
            success: function (resp) {
                var result=Ext.util.JSON.decode(resp.responseText);
                if(result.statusCode==200){
                    Ext.Msg.alert('成功', "股票和帖子关联成功");
                    stockSelectionModel.clearSelections();
                    postSelectionModel.clearSelections();
                    var postStockRelationStore = me.getPostStockRelationGrid().getStore();
                    postStockRelationStore.reload();
                }else{
                    Ext.Msg.alert('失败', result.message);
                }
            }
        });

    },

    /* 隐藏前事件 */
    onPostStockRelationGridBeforeHide: function(component, eOpts) {
        var me = this;
        if(me.getStockSelectGrid() == undefined){
            return ;
        }
        var stockSelectionModel = me.getStockSelectGrid().getSelectionModel();
        stockSelectionModel.clearSelections();
    }

});
