/*
 * File: app/controller/RelationStockController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GURUAdmin.controller.RelationStockController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.RelationStockController',

    refs: {
        addEssenceBt: '#addEssenceBt',
        cancelAddEssenceBt: '#cancelAddEssenceBt',
        relationStockGrid: '#RelationStockGrid',
        relationStockGridQueryFormSeacherBt: '#relationStockGridQueryFormSeacherBt',
        relationStockGridQueryForm: '#relationStockGridQueryForm'
    },

    control: {
        "#addEssenceBt": {
            click: 'onAddEssenceBtClick'
        },
        "#cancelAddEssenceBt": {
            click: 'onCancelAddEssenceBtClick'
        },
        "#relationStockGridQueryFormSeacherBt": {
            click: 'onRelationStockGridQueryFormSeacherBtClick'
        },
        "#RelationStockGrid": {
            beforehide: 'onRelationStockGridBeforeHide'
        }
    },

    /* 加精列表加精按钮事件 */
    onAddEssenceBtClick: function(button, e, eOpts) {
        var me = this;
        var relationStockGrid = this.getRelationStockGrid();
        var selectionModel = relationStockGrid.getSelectionModel();
        var record = selectionModel.getSelection();
        if (record===null || record===undefined || record.length===0) {
            Ext.MessageBox.alert('未选中', "请选中一行");
            return ;
        }else{
            var data=record[0].data;
            Ext.Ajax.request({
            headers: {
                'Content-Type': 'application/json'
            },
            url: "../api/post/addEssence?stockCode="+data.stockCode+"&postId="+data.postId,
            method: 'POST',
            success: function (resp) {
                var obj = Ext.util.JSON.decode(resp.responseText);
                Ext.MessageBox.alert('更新操作', "加精成功");
                me.getRelationStockGrid().getStore().reload();
            }
            });
        }


    },

    /* 取消加精按钮事件 */
    onCancelAddEssenceBtClick: function(button, e, eOpts) {
        var me = this;
        var relationStockGrid = this.getRelationStockGrid();
        var selectionModel = relationStockGrid.getSelectionModel();
        var record = selectionModel.getSelection();
        if (record===null || record===undefined || record.length===0) {
            Ext.MessageBox.alert('未选中', "请选中一行");
            return ;
        }else{
            var data=record[0].data;
            Ext.Ajax.request({
                headers: {
                    'Content-Type': 'application/json'
                },
                url: "../api/post/deleteEssence/"+data.stockCode+"/"+data.postId,
                method: 'DELETE',
                success: function (resp) {
                    var obj = Ext.util.JSON.decode(resp.responseText);
                    Ext.MessageBox.alert('更新操作', "取消加精成功");
                    me.getRelationStockGrid().getStore().reload();
                }
            });
        }
    },

    /* 加精列表搜索按钮 */
    onRelationStockGridQueryFormSeacherBtClick: function(button, e, eOpts) {
        var me = this;
        var form = me.getRelationStockGridQueryForm().getForm();
        var relationStockStore = this.getRelationStockGrid().getStore();
        relationStockStore.on('beforeload', function(store, options) {
            var queryParams = {
                stockCode : form.findField("stockCode").getValue()
            };
            Ext.apply(store.proxy.extraParams, queryParams);
        });
        relationStockStore.loadPage(1);
    },

    /* 隐藏前触发事件 */
    onRelationStockGridBeforeHide: function(component, eOpts) {
        this.getRelationStockGridQueryForm().reset();
    }

});
